In [0]:
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
import os 
os.chdir('/content/gdrive/My Drive/TradingBot')
os.getcwd()

'/content/gdrive/My Drive/TradingBot'

In [0]:
import torch
ckpt = torch.load('saves/a2c/checkpoints/checkpoint-2000000.pth')
state_dict = ckpt['state_dict']
torch.save(state_dict, 'saves/candidates/4.pth')

In [16]:
%reload_ext autoreload
%autoreload 2
# !python 01_train_dqn.py --cuda --colab --double
# !python 02_train_a2c.py --cuda --colab --year 2016
# !python 03_train_a3c.py --cuda 
# !python 04_train_ddpg.py --cuda --colab --year 2016
!python 02_play_a2c.py --cuda -y 2016 -m saves/a2c/best_mean_reward.pth

tensor([[ 1.4288, -1.6080]], device='cuda:0', grad_fn=<AddmmBackward>)
100: reward=-0.127, benchmark_reward=-0.110
tensor([[ 1.4850, -1.5803]], device='cuda:0', grad_fn=<AddmmBackward>)
200: reward=-0.113, benchmark_reward=-0.110
tensor([[ 1.3177, -1.4011]], device='cuda:0', grad_fn=<AddmmBackward>)
300: reward=-0.106, benchmark_reward=-0.110
tensor([[ 1.2156, -1.3596]], device='cuda:0', grad_fn=<AddmmBackward>)
400: reward=0.777, benchmark_reward=0.768
tensor([[ 1.7183, -1.7962]], device='cuda:0', grad_fn=<AddmmBackward>)
500: reward=-4.335, benchmark_reward=-4.281
tensor([[ 0.8373, -0.8955]], device='cuda:0', grad_fn=<AddmmBackward>)
600: reward=-4.335, benchmark_reward=-4.281
tensor([[ 4.9402, -5.4175]], device='cuda:0', grad_fn=<AddmmBackward>)
700: reward=-3.147, benchmark_reward=-3.183
tensor([[ 1.4274, -1.6383]], device='cuda:0', grad_fn=<AddmmBackward>)
800: reward=-2.122, benchmark_reward=-2.195
tensor([[ 1.4166, -1.5395]], device='cuda:0', grad_fn=<AddmmBackward>)
900: reward